// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface Metadata {
    __metadata: {
        modelName: string;
        urlPath?: string;
    };
}

export interface IBadge extends Metadata {
    /** Label */
    label: string;

    /** Element ID */
    elementId?: string | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IButton extends Metadata {
    /** Label */
    label?: string | undefined;

    /** Alt text */
    altText?: string | undefined;

    /** URL */
    url: string;

    /** Show icon */
    showIcon?: boolean | undefined;

    /** Icon */
    icon?:
        | 'apple'
        | 'arrowLeft'
        | 'arrowLeftCircle'
        | 'arrowRight'
        | 'arrowRightCircle'
        | 'cart'
        | 'chevronLeft'
        | 'chevronRight'
        | 'facebook'
        | 'github'
        | 'googlePlay'
        | 'instagram'
        | 'linkedin'
        | 'mail'
        | 'play'
        | 'playCircle'
        | 'reddit'
        | 'send'
        | 'twitter'
        | 'vimeo'
        | 'youtube'
        | undefined;

    /** Icon position */
    iconPosition?: 'left' | 'right' | undefined;

    /** Style */
    style?: 'primary' | 'secondary' | undefined;

    /** Element ID */
    elementId?: string | undefined;
}


export interface ICheckboxFormControl extends Metadata {
    /** Name */
    name: string;

    /** Label */
    label?: string | undefined;

    /** Is the field required? */
    isRequired?: boolean | undefined;

    /** Width */
    width?: 'full' | '1/2' | undefined;
}


export interface IConfig extends Metadata {
    /** Favicon */
    favicon?: Asset | undefined;

    /** Header configuration */
    header?: IHeader | undefined;

    /** Footer configuration */
    footer?: IFooter | undefined;
}


export interface IContactBlock extends Metadata {
    /** Title */
    title?: string | undefined;

    /** Phone number */
    phoneNumber?: string | undefined;

    /** Phone alt text */
    phoneAltText?: string | undefined;

    /** Email address */
    email?: string | undefined;

    /** Email address alt text */
    emailAltText?: string | undefined;

    /** Address */
    address?: string | undefined;

    /** Address alt text */
    addressAltText?: string | undefined;

    /** Element ID */
    elementId?: string | undefined;
}


export interface IContactSection extends Metadata {
    /** Element ID */
    elementId?: string | undefined;

    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Background size */
    backgroundSize?: 'full' | 'inset' | undefined;

    /** Title */
    title?: string | undefined;

    /** Text */
    text?: string | undefined;

    /** Form */
    form?: IFormBlock | undefined;

    /** Media */
    media?: IImageBlock | IVideoBlock | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface ICtaSection extends Metadata {
    /** Element ID */
    elementId?: string | undefined;

    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Background size */
    backgroundSize?: 'full' | 'inset' | undefined;

    /** Title */
    title?: string | undefined;

    /** Text */
    text?: string | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Background image */
    backgroundImage?: IImageBlock | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IEmailFormControl extends Metadata {
    /** Name */
    name?: string | undefined;

    /** Label */
    label?: string | undefined;

    /** Hide label */
    hideLabel?: boolean | undefined;

    /** Placeholder text */
    placeholder?: string | undefined;

    /** Is the field required? */
    isRequired?: boolean | undefined;

    /** Width */
    width?: 'full' | '1/2' | undefined;
}


export interface IFaqItem extends Metadata {
    /** Question */
    question: string;

    /** Answer */
    answer: string;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IFaqSection extends Metadata {
    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Title */
    title?: string | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Items */
    items?: IFaqItem[] | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IFeaturedItem extends Metadata {
    /** Element ID */
    elementId?: string | undefined;

    /** Title */
    title?: string | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Text */
    text?: string | undefined;

    /** Image */
    featuredImage?: IImageBlock | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IFeaturedItemsSection extends Metadata {
    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Title */
    title?: string | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Items */
    items?: IFeaturedItem[] | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Items per row */
    columns?: number | undefined;

    /** Enable hover */
    enableHover?: boolean | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IFeaturedPeopleSection extends Metadata {
    /** Element ID */
    elementId?: string | undefined;

    /** Arrangement */
    variant?: 'variant-a' | 'variant-b' | 'variant-c' | undefined;

    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Title */
    title?: string | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** People */
    people?: IPerson[] | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IFeaturedPostsSection extends Metadata {
    /** Element ID */
    elementId?: string | undefined;

    /** Show post date */
    showDate?: boolean | undefined;

    /** Show post author */
    showAuthor?: boolean | undefined;

    /** Show post excerpt */
    showExcerpt?: boolean | undefined;

    /** Arrangement */
    variant?: 'variant-a' | 'variant-b' | 'variant-c' | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;

    /** Title */
    title?: string | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Posts */
    posts?: IPostLayout[] | undefined;
}


export interface IFeatureHighlightSection extends Metadata {
    /** Element ID */
    elementId?: string | undefined;

    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Background size */
    backgroundSize?: 'full' | 'inset' | undefined;

    /** Title */
    title?: string | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Badge */
    badge?: IBadge | undefined;

    /** Text */
    text?: string | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Media */
    media?: IImageBlock | IVideoBlock | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IFooter extends Metadata {
    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Logo */
    logo?: IImageBlock | undefined;

    /** Title */
    title?: string | undefined;

    /** Text */
    text?: string | undefined;

    /** Contacts */
    contacts?: IContactBlock | undefined;

    /** Copyright text */
    copyrightText?: string | undefined;

    /** Primary navigation links */
    primaryLinks?: (IButton | ILink)[] | undefined;

    /** Social links */
    socialLinks?: ISocial[] | undefined;

    /** Legal navigation links */
    legalLinks?: (IButton | ILink)[] | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IFormBlock extends Metadata {
    /** Form arrangement */
    variant?: 'variant-a' | 'variant-b' | undefined;

    /** Fields */
    fields?: (ITextFormControl | IEmailFormControl | ITextareaFormControl | ICheckboxFormControl | ISelectFormControl)[] | undefined;

    /** Button */
    submitLabel?: string | undefined;

    /** Element ID */
    elementId: string;

    /** Action (form submission URL) */
    action?: string | undefined;

    /** Destination (email to redirect responses) */
    destination?: string | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IHeader extends Metadata {
    /** Header arrangement */
    headerVariant?: 'variant-a' | 'variant-b' | 'variant-c' | 'variant-d' | 'variant-e' | undefined;

    /** Primary colors */
    primaryColors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Secondary colors (mobile menu) */
    secondaryColors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Title */
    title?: string | undefined;

    /** Display title */
    isTitleVisible?: boolean | undefined;

    /** Logo */
    logo?: IImageBlock | undefined;

    /** Primary navigation links */
    primaryLinks?: (IButton | ILink)[] | undefined;

    /** Secondary links */
    secondaryLinks?: (IButton | ILink)[] | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IHeroSection extends Metadata {
    /** Element ID */
    elementId?: string | undefined;

    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Title */
    title?: string | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Badge */
    badge?: IBadge | undefined;

    /** Text */
    text?: string | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Media */
    media?: IFormBlock | IImageBlock | IVideoBlock | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IImageBlock extends Metadata {
    /** Image */
    url?: Asset | undefined;

    /** Alt text */
    altText?: string | undefined;

    /** Caption */
    caption?: string | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IJobList extends Metadata {
    /** Title */
    title?: string | undefined;

    /** Items */
    items?: IJobListItem[] | undefined;
}


export interface IJobListItem extends Metadata {
    /** Title */
    title?: string | undefined;

    /** Location */
    location?: string | undefined;

    /** Text */
    text?: string | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;
}


export interface IJobsSection extends Metadata {
    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Title */
    title?: string | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Job lists */
    jobLists?: IJobList[] | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface ILink extends Metadata {
    /** Label */
    label?: string | undefined;

    /** Alt text */
    altText?: string | undefined;

    /** URL */
    url: string;

    /** Show icon */
    showIcon?: boolean | undefined;

    /** Icon */
    icon?:
        | 'apple'
        | 'arrowLeft'
        | 'arrowLeftCircle'
        | 'arrowRight'
        | 'arrowRightCircle'
        | 'cart'
        | 'chevronLeft'
        | 'chevronRight'
        | 'facebook'
        | 'github'
        | 'googlePlay'
        | 'instagram'
        | 'linkedin'
        | 'mail'
        | 'play'
        | 'playCircle'
        | 'reddit'
        | 'send'
        | 'twitter'
        | 'vimeo'
        | 'youtube'
        | undefined;

    /** Icon position */
    iconPosition?: 'left' | 'right' | undefined;

    /** Element ID */
    elementId?: string | undefined;
}


export interface IMediaGallerySection extends Metadata {
    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Title */
    title?: string | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Images */
    images?: IImageBlock[] | undefined;

    /** Spacing between images */
    spacing?: number | undefined;

    /** Images per row */
    columns?: number | undefined;

    /** Image aspect ratio */
    aspectRatio?: '1:1' | '3:2' | '2:3' | '4:3' | '3:4' | '16:9' | 'auto' | undefined;

    /** Max image size, in px */
    imageSizePx?: number | undefined;

    /** Show caption */
    showCaption?: boolean | undefined;

    /** Enable hover */
    enableHover?: boolean | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IPagedPostsSection extends Metadata {
    /** Element ID */
    elementId?: string | undefined;

    /** Show post excerpt */
    showExcerpt?: boolean | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;

    /** Title */
    title?: string | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Show Date */
    showDate?: boolean | undefined;

    /** Show Author */
    showAuthor?: boolean | undefined;

    /** Variant */
    variant?: 'variant-a' | 'variant-b' | 'variant-c' | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;
}


export interface IPageLayout extends Metadata {
    /** Title */
    title: string;

    /** Slug */
    slug: string;

    /** Sections */
    sections?:
        | (
              | IContactSection
              | ICtaSection
              | IFaqSection
              | IFeatureHighlightSection
              | IFeaturedItemsSection
              | IFeaturedPeopleSection
              | IFeaturedPostsSection
              | IHeroSection
              | IJobsSection
              | IMediaGallerySection
              | IQuoteSection
              | IRecentPostsSection
              | ITestimonialsSection
              | ITextSection
          )[]
        | undefined;
}


export interface IPerson extends Metadata {
    /** First name */
    firstName: string;

    /** Last name */
    lastName?: string | undefined;

    /** Role */
    role?: string | undefined;

    /** Bio */
    bio?: string | undefined;

    /** Image */
    image?: IImageBlock | undefined;
}


export interface IPostFeedLayout extends Metadata {
    /** Title */
    title?: string | undefined;

    /** Slug */
    slug: string;

    /** Number of Posts per page */
    numOfPostsPerPage?: number | undefined;

    /** Post Feed */
    postFeed?: IPagedPostsSection | undefined;

    /** Top Sections */
    topSections?:
        | (
              | IContactSection
              | ICtaSection
              | IFaqSection
              | IFeatureHighlightSection
              | IFeaturedItemsSection
              | IFeaturedPeopleSection
              | IFeaturedPostsSection
              | IHeroSection
              | IJobsSection
              | IMediaGallerySection
              | IQuoteSection
              | IRecentPostsSection
              | ITestimonialsSection
              | ITextSection
          )[]
        | undefined;

    /** Bottom Sections */
    bottomSections?:
        | (
              | IContactSection
              | ICtaSection
              | IFaqSection
              | IFeatureHighlightSection
              | IFeaturedItemsSection
              | IFeaturedPeopleSection
              | IFeaturedPostsSection
              | IHeroSection
              | IJobsSection
              | IMediaGallerySection
              | IQuoteSection
              | IRecentPostsSection
              | ITestimonialsSection
              | ITextSection
          )[]
        | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IPostFeedSection extends Metadata {
    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Title */
    title?: string | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Show post date */
    showDate?: boolean | undefined;

    /** Show post author */
    showAuthor?: boolean | undefined;

    /** Show post excerpt */
    showExcerpt?: boolean | undefined;

    /** Arrangement */
    variant?: 'variant-a' | 'variant-b' | 'variant-c' | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IPostLayout extends Metadata {
    /** Title */
    title: string;

    /** Slug */
    slug: string;

    /** Date */
    date: string;

    /** Author */
    author?: IPerson | undefined;

    /** Excerpt */
    excerpt?: string | undefined;

    /** Featured image */
    featuredImage?: IImageBlock | undefined;

    /** Sections */
    bottomSections?:
        | (
              | IContactSection
              | ICtaSection
              | IFaqSection
              | IFeatureHighlightSection
              | IFeaturedItemsSection
              | IFeaturedPeopleSection
              | IFeaturedPostsSection
              | IHeroSection
              | IJobsSection
              | IMediaGallerySection
              | IQuoteSection
              | IRecentPostsSection
              | ITestimonialsSection
              | ITextSection
          )[]
        | undefined;

    /** Content */
    content?: string | undefined;
}


export interface IQuoteSection extends Metadata {
    /** Element ID */
    elementId?: string | undefined;

    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Quote */
    quote: string;

    /** Author name */
    name?: string | undefined;

    /** Author title */
    title?: string | undefined;

    /** Background image */
    backgroundImage?: IImageBlock | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IRecentPostsSection extends Metadata {
    /** Element ID */
    elementId?: string | undefined;

    /** Show post date */
    showDate?: boolean | undefined;

    /** Show post author */
    showAuthor?: boolean | undefined;

    /** Show post excerpt */
    showExcerpt?: boolean | undefined;

    /** Arrangement */
    variant?: 'variant-a' | 'variant-b' | 'variant-c' | undefined;

    /** Actions */
    actions?: (IButton | ILink)[] | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;

    /** Title */
    title?: string | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Number of recent posts to show */
    recentCount?: number | undefined;
}


export interface ISelectFormControl extends Metadata {
    /** Name */
    name: string;

    /** Label */
    label?: string | undefined;

    /** Hide label */
    hideLabel?: boolean | undefined;

    /** Default value */
    defaultValue?: string | undefined;

    /** Options */
    options?: string[] | undefined;

    /** Is the field required? */
    isRequired?: boolean | undefined;

    /** Width */
    width?: 'full' | '1/2' | undefined;
}


export interface ISocial extends Metadata {
    /** Label */
    label?: string | undefined;

    /** Alt text */
    altText?: string | undefined;

    /** URL */
    url: string;

    /** Icon */
    icon?: 'facebook' | 'github' | 'instagram' | 'linkedin' | 'reddit' | 'twitter' | 'vimeo' | 'youtube' | undefined;

    /** Style */
    style?: 'link' | 'primary' | 'secondary' | undefined;

    /** Element ID */
    elementId?: string | undefined;
}


export interface ITestimonial extends Metadata {
    /** Quote */
    quote: string;

    /** Author name */
    name?: string | undefined;

    /** Author title */
    title?: string | undefined;

    /** Author image */
    image?: IImageBlock | undefined;

    /** Element ID */
    elementId?: string | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface ITestimonialsSection extends Metadata {
    /** Element ID */
    elementId?: string | undefined;

    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Arrangement */
    variant?: 'variant-a' | 'variant-b' | 'variant-c' | undefined;

    /** Title */
    title?: string | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Testimonials */
    testimonials?: ITestimonial[] | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface ITextareaFormControl extends Metadata {
    /** Name */
    name: string;

    /** Label */
    label?: string | undefined;

    /** Hide label */
    hideLabel?: boolean | undefined;

    /** Placeholder text */
    placeholder?: string | undefined;

    /** Is the field required? */
    isRequired?: boolean | undefined;

    /** Width */
    width?: 'full' | '1/2' | undefined;
}


export interface ITextFormControl extends Metadata {
    /** Name */
    name: string;

    /** Label */
    label?: string | undefined;

    /** Hide label */
    hideLabel?: boolean | undefined;

    /** Placeholder text */
    placeholder?: string | undefined;

    /** Is the field required? */
    isRequired?: boolean | undefined;

    /** Width */
    width?: 'full' | '1/2' | undefined;
}


export interface ITextSection extends Metadata {
    /** Element ID */
    elementId?: string | undefined;

    /** Colors */
    colors?: 'colors-a' | 'colors-b' | 'colors-c' | 'colors-d' | 'colors-e' | 'colors-f' | 'colors-g' | 'colors-h' | undefined;

    /** Title */
    title?: string | undefined;

    /** Subtitle */
    subtitle?: string | undefined;

    /** Text */
    text?: string | undefined;

    /** Styles */
    styles?: Record<string, any> | undefined;
}


export interface IThemeStyle extends Metadata {
    /** Font - headlines & subtitles */
    fontHeadlines?: 'sans' | 'sansAlt' | undefined;

    /** H1 */
    h1?: IThemeStyleHeading | undefined;

    /** H2 */
    h2?: IThemeStyleHeading | undefined;

    /** H3 */
    h3?: IThemeStyleHeading | undefined;

    /** H4 */
    h4?: IThemeStyleHeading | undefined;

    /** H5 */
    h5?: IThemeStyleHeading | undefined;

    /** H6 */
    h6?: IThemeStyleHeading | undefined;

    /** Font - body & captions */
    fontBody?: 'sans' | 'sansAlt' | undefined;

    /** Site background */
    main?: string | undefined;

    /** Light */
    light?: string | undefined;

    /** Foreground over light */
    onLight?: string | undefined;

    /** Dark */
    dark?: string | undefined;

    /** Foreground over dark */
    onDark?: string | undefined;

    /** Primary */
    primary?: string | undefined;

    /** Foreground over primary */
    onPrimary?: string | undefined;

    /** Secondary */
    secondary?: string | undefined;

    /** Foreground over secondary */
    onSecondary?: string | undefined;

    /** Complementary */
    complementary?: string | undefined;

    /** Foreground over complementary */
    onComplementary?: string | undefined;

    /** Primary button */
    buttonPrimary?: IThemeStyleButton | undefined;

    /** Secondary button */
    buttonSecondary?: IThemeStyleButton | undefined;

    /** Link */
    link?: IThemeStyleButton | undefined;
}


export interface IThemeStyleButton extends Metadata {
    /** Font weight */
    weight?: 'normal' | 'bold' | undefined;

    /** Case */
    case?: 'none' | 'lowercase' | 'capitalize' | 'uppercase' | undefined;

    /** Letter spacing */
    letterSpacing?: 'tighter' | 'tight' | 'normal' | 'wide' | 'wider' | undefined;

    /** Corner radius */
    borderRadius?: 'none' | 'md' | 'full' | undefined;

    /** Border style */
    borderStyle?: 'none' | 'solid' | 'dashed' | 'dotted' | 'double' | undefined;

    /** Horizontal padding */
    horizontalPadding?: number | undefined;

    /** Vertical padding */
    verticalPadding?: number | undefined;

    /** Shadow */
    shadow?: 'none' | 'md' | 'xl' | undefined;
}


export interface IThemeStyleHeading extends Metadata {
    /** Font size */
    size?: 'xs' | 'sm' | 'base' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl' | '5xl' | '6xl' | '7xl' | '8xl' | '9xl' | undefined;

    /** Font weight */
    weight?: 'normal' | 'bold' | undefined;

    /** Decoration */
    decoration?: 'none' | 'underline' | 'line-through' | undefined;

    /** Case */
    case?: 'none' | 'lowercase' | 'capitalize' | 'uppercase' | undefined;

    /** Letter spacing */
    letterSpacing?: 'tighter' | 'tight' | 'normal' | 'wide' | 'wider' | undefined;
}


export interface IVideoBlock extends Metadata {
    /** Title */
    title?: string | undefined;

    /** Video URL (YouTube, Vimeo, .mp4) */
    url?: string | undefined;

    /** Autoplay */
    autoplay?: boolean | undefined;

    /** Loop */
    loop?: boolean | undefined;

    /** Muted */
    muted?: boolean | undefined;

    /** Controls */
    controls?: boolean | undefined;

    /** Aspect ratio */
    aspectRatio?: '4:3' | '16:9' | undefined;

    /** Element ID */
    elementId?: string | undefined;
}


export type CONTENT_TYPE =
    | 'Badge'
    | 'Button'
    | 'CheckboxFormControl'
    | 'Config'
    | 'ContactBlock'
    | 'ContactSection'
    | 'CtaSection'
    | 'EmailFormControl'
    | 'FaqItem'
    | 'FaqSection'
    | 'FeaturedItem'
    | 'FeaturedItemsSection'
    | 'FeaturedPeopleSection'
    | 'FeaturedPostsSection'
    | 'FeatureHighlightSection'
    | 'Footer'
    | 'FormBlock'
    | 'Header'
    | 'HeroSection'
    | 'ImageBlock'
    | 'JobList'
    | 'JobListItem'
    | 'JobsSection'
    | 'Link'
    | 'MediaGallerySection'
    | 'PagedPostsSection'
    | 'PageLayout'
    | 'Person'
    | 'PostFeedLayout'
    | 'PostFeedSection'
    | 'PostLayout'
    | 'QuoteSection'
    | 'RecentPostsSection'
    | 'SelectFormControl'
    | 'Social'
    | 'Testimonial'
    | 'TestimonialsSection'
    | 'TextareaFormControl'
    | 'TextFormControl'
    | 'TextSection'
    | 'ThemeStyle'
    | 'ThemeStyleButton'
    | 'ThemeStyleHeading'
    | 'VideoBlock';

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
